spring:
  main:
    banner-mode: off
  shell:
    interactive:
      enabled: true
## disable console logging
logging:
  pattern:
    console:
## log debug from a cli
  # file:
  #   name: shell-ffm.log
  # level:
  #   root: debug
  #   org:
  #     springframework:
  #       shell: debug
