spring:
  main:
    banner-mode: off
  shell:
    config:
      env: SPRING_SHELL_SAMPLES_USER_HOME
      location: "{userconfig}/spring-shell-samples"
    history:
      name: spring-shell-samples-history.log
    command:
      help:
        grouping-mode: group
      completion:
        root-command: spring-shell-samples
## disable console logging
logging:
  pattern:
    console:
## log debug from a cli
#  file:
#    name: shell.log
#  level:
#    root: debug
#    org:
#      springframework:
#        shell: debug
