name: Schedule e2e

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1,3,5'

permissions:
  actions: write

jobs:
  dispatch_e2e:
    name: Dispatch e2e
    if: github.repository_owner == 'spring-projects'
    strategy:
      matrix:
        branch: [ main, 3.2.x, 3.1.x ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Dispatch
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: gh workflow run e2e.yml -r ${{ matrix.branch }}
